sudo: false

language: node_js

matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4"
      env: COVERALLS=1
    - node_js: "6"

after_success:
  - if [ "x$COVERALLS" = "x1" ]; then npm run coveralls; fi
